# -*- coding: utf-8 -*-
"""NeuralDiscreteRepresentationLearning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/vishal2028/neuraldiscreterepresentationlearning.e162f25a-31cd-4ab3-b518-24ca52ab9528.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260612/auto/storage/goog4_request%26X-Goog-Date%3D20260612T165128Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Db178478d7c5d0afce4c16aaf47388072a4edb50d3d0942ca4e36cff2462f861996da868f54d2c8fc747843a4d89528421afd07b8d0b0e6ec85981f8ece9ccc263e1f1e0e3e02855344ed052537294518bdaaed38b61061ac5680412be2e0407045ec2e48cd934667bbd3ed405a25fffe0f828e5a7699a007dd5bdaa1ca5f1e87ea03ad5262232469752feec990f60a9ca7a371c534f25837009318fad5c52e0349ed8261cc4473e461eef90fe453383bbbbb5b88b92644a30dbb8fb4f27fb780db6e18b668e88e520a7dad4ff9515845f7ac73fd69bf595895b52219ec81eeb1954d4d2dfd4dd23f6d5f4aa3cb870d47e64c011a99df95a9460de919c38d2e72
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

jessicali9530_celeba_dataset_path = kagglehub.dataset_download('jessicali9530/celeba-dataset')
vishal2028_checkpoints_path = kagglehub.dataset_download('vishal2028/checkpoints')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

import os

for item in os.listdir('/kaggle/input/datasets/jessicali9530/celeba-dataset'):
    print(item)

import os
import glob
from PIL import Image
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision import transforms
import matplotlib.pyplot as plt
import torchvision.utils as vutils
import numpy as np

# 1. The Auto-Path Finder (THE FIX)
print("Hunting for CelebA images...")
# Search for any .jpg file inside the Kaggle input directory
sample_images = glob.glob('/kaggle/input/**/*.jpg', recursive=True)

if not sample_images:
    raise RuntimeError("Could not find any .jpg files! Make sure the CelebA dataset is added to your notebook.")

# Extract the exact directory path from the first image we found
data_path = os.path.dirname(sample_images[0])
print(f"Found the images! Setting data_path to: {data_path}\n")

# 2. Custom Dataset Class
class CelebADataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir = root_dir
        self.image_files = [f for f in os.listdir(root_dir) if f.endswith('.jpg')]
        self.transform = transform

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        img_path = os.path.join(self.root_dir, self.image_files[idx])
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, 0

# 3. Preprocessing Transforms
image_size = 64
transform = transforms.Compose([
    transforms.CenterCrop(178),
    transforms.Resize((image_size, image_size)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

# 4. Initialize and Sub-sample
full_dataset = CelebADataset(root_dir=data_path, transform=transform)

# Ensure we don't ask for 5000 images if the dataset somehow has less
DEBUG_SIZE =  len(full_dataset)
debug_indices = list(range(DEBUG_SIZE))
debug_dataset = Subset(full_dataset, debug_indices)

# 5. Create the DataLoader
dataloader = DataLoader(debug_dataset, batch_size=128, shuffle=True, num_workers=4, pin_memory=True)

print(f"Total dataset size: {len(full_dataset)}")
print(f"Subset size for fast debugging: {len(debug_dataset)}")

# Grab one batch of real images
images, _ = next(iter(dataloader))

print("--- PIPELINE SANITY CHECK ---")
print(f"Batch Tensor Shape: {images.shape}")
print(f"Value Range: Min = {images.min().item():.2f}, Max = {images.max().item():.2f}")
print("-----------------------------\n")

# Expected Shape check
if images.shape == torch.Size([128, 3, 64, 64]):
    print("SUCCESS: Data shape matches expected dimensions perfectly. Proceeding to grid layout...")
else:
    print("WARNING: Shape mismatch! Fix the data pipeline before proceeding.")

# Plot the grid of faces
grid = vutils.make_grid(images[:16], nrow=4, normalize=True)
plt.figure(figsize=(8, 8))
plt.imshow(np.transpose(grid.cpu(), (1, 2, 0)))
plt.axis("off")
plt.title("Sanity Check: Centered & Normalized Faces")
plt.show()

class CelebAEncoder(nn.Module):
    def __init__(self, in_channels=3, latent_dim=256):
        super().__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channels, 64, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(64),
            nn.LeakyReLU(0.2)
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2)
        )
        self.conv3 = nn.Sequential(
            nn.Conv2d(128, latent_dim, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(latent_dim)
        )

    def forward(self, x, debug=False):
        if debug: print(f"Encoder Input: {x.shape}")
        x = self.conv1(x)
        if debug: print(f"After Conv1:   {x.shape}")
        x = self.conv2(x)
        if debug: print(f"After Conv2:   {x.shape}")
        x = self.conv3(x)
        if debug: print(f"After Conv3:   {x.shape}")
        return x

class CelebADecoder(nn.Module):
    def __init__(self, out_channels=3, latent_dim=256):
        super().__init__()
        self.deconv1 = nn.Sequential(
            nn.ConvTranspose2d(latent_dim, 128, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU()
        )
        self.deconv2 = nn.Sequential(
            nn.ConvTranspose2d(128, 64, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU()
        )
        self.deconv3 = nn.Sequential(
            nn.ConvTranspose2d(64, out_channels, kernel_size=4, stride=2, padding=1),
            nn.Tanh() # Output range perfectly matches [-1, 1]
        )

    def forward(self, x, debug=False):
        if debug: print(f"\nDecoder Input: {x.shape}")
        x = self.deconv1(x)
        if debug: print(f"After Deconv1: {x.shape}")
        x = self.deconv2(x)
        if debug: print(f"After Deconv2: {x.shape}")
        x = self.deconv3(x)
        if debug: print(f"After Deconv3: {x.shape}")
        return x

# 1. Instantiate the newly defined models
encoder = CelebAEncoder(latent_dim=256)
decoder = CelebADecoder(latent_dim=256)

# 2. Grab a real batch of your 64x64 faces
images, _ = next(iter(dataloader))

# 3. Test forward passes with debugging output activated
print("--- ENCODER DOWNSAMPLING ---")
z = encoder(images, debug=True)

print("\n--- DECODER UPSAMPLING ---")
recon = decoder(z, debug=True)

print("\n--- SHAPE VALIDATION ---")
if recon.shape == images.shape:
    print("SUCCESS: Structural symmetry verified. Ready to implement the Vector Quantizer module!")
else:
    print(f"ERROR: Symmetrical shape mismatch! Original: {images.shape}, Reconstructed: {recon.shape}")

import torch
import torch.nn as nn
import torch.nn.functional as F

class VectorQuantizerEMA(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, commitment_cost=0.25, decay=0.99, epsilon=1e-5):
        super().__init__()
        self.num_embeddings = num_embeddings
        self.embedding_dim = embedding_dim
        self.commitment_cost = commitment_cost

        # EMA specific parameters
        self.decay = decay
        self.epsilon = epsilon

        # Initialize embeddings
        self.embedding = nn.Embedding(num_embeddings, embedding_dim)
        self.embedding.weight.data.uniform_(-1/num_embeddings, 1/num_embeddings)

        # Buffers for EMA (these update during forward passes but don't use Adam)
        self.register_buffer("ema_cluster_size", torch.zeros(num_embeddings))
        self.register_buffer("ema_w", self.embedding.weight.data.clone())

    def forward(self, x):
        # Flatten input
        flat_x = x.permute(0, 2, 3, 1).contiguous().view(-1, self.embedding_dim)

        # Calculate distances
        distances = (torch.sum(flat_x**2, dim=1, keepdim=True)
                     + torch.sum(self.embedding.weight**2, dim=1)
                     - 2 * torch.matmul(flat_x, self.embedding.weight.t()))

        # Find closest encodings
        encoding_indices = torch.argmin(distances, dim=1)

        # [RESTORED FIX] View as [Batch, Height, Width, Channels] first, THEN permute to [Batch, Channels, Height, Width]
        quantized = self.embedding(encoding_indices).view(x.shape[0], x.shape[2], x.shape[3], self.embedding_dim)
        quantized = quantized.permute(0, 3, 1, 2).contiguous()

        # EMA Updates (Only during training!)
        if self.training:
            encodings = F.one_hot(encoding_indices, self.num_embeddings).float()

            # Update cluster sizes
            n = torch.sum(encodings, dim=0)
            self.ema_cluster_size = self.ema_cluster_size * self.decay + n * (1 - self.decay)

            # Laplace smoothing
            n_sum = torch.sum(self.ema_cluster_size)
            self.ema_cluster_size = ((self.ema_cluster_size + self.epsilon) /
                                     (n_sum + self.num_embeddings * self.epsilon) * n_sum)

            # Update weights
            dw = torch.matmul(encodings.t(), flat_x)
            self.ema_w = self.ema_w * self.decay + dw * (1 - self.decay)
            self.embedding.weight.data = self.ema_w / self.ema_cluster_size.unsqueeze(1)

        # The Commitment Loss
        e_latent_loss = F.mse_loss(quantized.detach(), x)
        commitment_loss = self.commitment_cost * e_latent_loss

        # Straight-through estimator
        quantized = x + (quantized - x).detach()

        return quantized, commitment_loss, encoding_indices.view(x.shape[0], x.shape[2], x.shape[3])

# ==========================================
# 2. Update the VQ-VAE Wrapper
# ==========================================
class CelebAVQVAE(nn.Module):
    def __init__(self, latent_dim=256, num_embeddings=512):
        super().__init__()

        # [RESTORED FIX] Explicitly use keyword arguments!
        self.encoder = CelebAEncoder(latent_dim=latent_dim)
        self.vq_layer = VectorQuantizerEMA(num_embeddings, latent_dim, commitment_cost=0.25)
        self.decoder = CelebADecoder(latent_dim=latent_dim)

    def forward(self, x):
        z = self.encoder(x)
        quantized, vq_loss, encodings = self.vq_layer(z)
        x_recon = self.decoder(quantized)
        return x_recon, vq_loss, encodings

import torch
import torch.nn as nn

model = CelebAVQVAE(latent_dim=256, num_embeddings=512)

if torch.cuda.device_count() > 1:
    print(f"Using {torch.cuda.device_count()} GPUs")
    model = nn.DataParallel(model)

device = torch.device("cuda")
model = model.to(device)

images = images.to(device)

reconstructed_images, vq_loss, encodings = model(images)
if torch.cuda.device_count() > 1:
    vq_loss = vq_loss.mean()

print("--- FINAL ARCHITECTURE VALIDATION ---")
print(f"Original Image Shape:      {images.shape}")
print(f"Reconstructed Image Shape: {reconstructed_images.shape}")
print(f"Codebook VQ Loss:          {vq_loss.item():.4f}")
print(f"Extracted Indices Shape:   {encodings.shape}")

if images.shape == reconstructed_images.shape:
    print("\nSUCCESS: The VQ-VAE is fully wired and mathematically sound.")
    print("Note: The Extracted Indices shape should be [128, 8, 8] representing the spatial grid of discrete codes for each image in the batch.")

import torch.optim as optim
import numpy as np
import gc
# --- NEW: Explicitly clear zombie memory before starting ---
gc.collect()
torch.cuda.empty_cache()
# -----------------------------------------------------------
scaler = torch.cuda.amp.GradScaler()
# 1. Hyperparameters for Debug Run
num_epochs = 25
learning_rate = 2e-4

# We use Adam, the standard optimizer for VQ-VAEs
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# 2. Tracking Arrays for our Visualizations
train_recon_errors = []
train_vq_errors = []

print("🚀 Starting VQ-VAE Training Loop...")
model.train() # Put model in training mode

for epoch in range(num_epochs):
    epoch_recon_loss = 0
    epoch_vq_loss = 0
    all_encodings = []

    for batch_idx, (images, _) in enumerate(dataloader):
        images = images.to(device)
        optimizer.zero_grad(set_to_none=True)

        # Calculate data variance for this batch to normalize MSE
        # This keeps the loss scale consistent across different batches
        data_variance = torch.var(images)

        with torch.autocast(device_type='cuda', dtype=torch.float16):
            reconstructed, vq_loss, encodings = model(images)
            # Average the VQ loss across all GPUs
            vq_loss = vq_loss.mean()
            recon_loss = torch.mean((reconstructed - images)**2) / data_variance
            loss = recon_loss + vq_loss

        # Backward pass & Optimize
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        # Track metrics
        epoch_recon_loss += recon_loss.item()
        epoch_vq_loss += vq_loss.item()

        # Save the 8x8 index maps, flattened, to check for Codebook Collapse later
        all_encodings.append(encodings.reshape(-1).cpu().detach().numpy())

    # Average the losses for the epoch
    avg_recon = epoch_recon_loss / len(dataloader)
    avg_vq = epoch_vq_loss / len(dataloader)

    train_recon_errors.append(avg_recon)
    train_vq_errors.append(avg_vq)

    print(f"Epoch [{epoch+1}/{num_epochs}] | Recon Loss: {avg_recon:.4f} | VQ Loss: {avg_vq:.4f}")

print("🎉 Debug Training Complete!")

import torch
import torch.nn as nn

print("🔄 Initiating Checkpoint Recovery...")

# 1. Re-instantiate the blank architecture
model = CelebAVQVAE(latent_dim=256, num_embeddings=512)

# 2. Point to the files you just uploaded
# IMPORTANT: Check your exact folder name in the right sidebar!
dataset_folder = '/kaggle/input/datasets/vishal2028/checkpoints'
weights_path = f'{dataset_folder}/vqvae_final_weights.pth'
latents_path = f'{dataset_folder}/celeba_8x8_latents (1).npy'

# 3. Load the weights into the blank model
# We load to CPU first to prevent memory spikes, then move to GPU
state_dict = torch.load(weights_path, map_location='cpu', weights_only=True)
model.load_state_dict(state_dict)

# 4. Set up the devices and DataParallel just like before
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

if torch.cuda.device_count() > 1:
    print(f"⚡ Rewiring to {torch.cuda.device_count()} GPUs...")
    model = nn.DataParallel(model)

model.eval()
print("✅ VQ-VAE fully recovered and ready for inference!")

import matplotlib.pyplot as plt
import numpy as np
import torchvision.utils as vutils

# ==========================================
# VISUALIZATION 1: Loss Curves
# ==========================================
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(train_recon_errors, color='blue', marker='o')
axes[0].set_title("Reconstruction Loss")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Normalized MSE")
axes[0].grid(True, alpha=0.3)

axes[1].plot(train_vq_errors, color='red', marker='o')
axes[1].set_title("VQ Codebook Loss")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Loss")
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/kaggle/working/vqvae_loss_curves.png', dpi=300, bbox_inches='tight')
print("💾 Saved Loss Curves to /kaggle/working/vqvae_loss_curves.png")
plt.show()

# ==========================================
# VISUALIZATION 2: Codebook Usage Histogram (PATCHED)
# ==========================================

# 1. Safely extract the base model from the DataParallel wrapper
base_model = model.module if isinstance(model, nn.DataParallel) else model

# 2. Grab the encodings. Since we wipe the array every epoch now,
# it only holds the final epoch's data, which is perfectly safe for RAM.
recent_encodings = np.concatenate(all_encodings)
num_codes = base_model.vq_layer.num_embeddings

# 3. Use numpy to count the frequencies (1000x faster than plt.hist)
unique_codes_used, counts = np.unique(recent_encodings, return_counts=True)

plt.figure(figsize=(12, 4))
# 4. Plot a simple bar chart of the pre-computed counts
plt.bar(unique_codes_used, counts, color='purple', alpha=0.7, width=1.0)
plt.title(f"Codebook Usage Histogram (Final Epoch)")
plt.xlabel("Codebook Index (0 to 511)")
plt.ylabel("Frequency of Use")
plt.xlim(0, num_codes)
plt.savefig('/kaggle/working/codebook_histogram.png', dpi=300, bbox_inches='tight')
print("💾 Saved Histogram to /kaggle/working/codebook_histogram.png")
plt.show()

# Calculate and print active codes
total_active = len(unique_codes_used)
print(f"📊 Active Codebook Vectors: {total_active} / {num_codes}")
if total_active < num_codes * 0.1:
    print("⚠️ WARNING: Severe Codebook Collapse detected! Most codes are dead.")
elif total_active < num_codes * 0.5:
    print("⚠️ NOTICE: Mild Codebook Collapse. This is common in early epochs.")
else:
    print("✅ HEALTHY: Excellent codebook utilization!")

import torch

# Extract the base model (in case of DataParallel) just to be safe
base_vq_model = model.module if isinstance(model, torch.nn.DataParallel) else model

# Save the weights to Kaggle's working directory
torch.save(base_vq_model.state_dict(), '/kaggle/working/vqvae_final_weights.pth')
print("💾 VQ-VAE Weights safely bolted to the hard drive!")

import torch
import numpy as np
from tqdm import tqdm
import torch.nn as nn

# 1. Put the model in evaluation mode
model.eval()

# --- THE FIX: Extract base model from DataParallel ---
base_model = model.module if isinstance(model, nn.DataParallel) else model
# ---------------------------------------------------

# 2. Array to hold our discrete 8x8 maps
all_latent_codes = []

print("📦 Extracting 8x8 discrete tokens from the full dataset...")

# 3. Pass the entire dataset through the frozen encoder
with torch.no_grad():
    for images, _ in tqdm(dataloader):
        images = images.to(device)

        # Use base_model here!
        z = base_model.encoder(images)

        # Use base_model here!
        _, _, encodings = base_model.vq_layer(z)

        # encodings shape is [Batch, 8, 8]. Convert to uint16 to save disk space
        all_latent_codes.append(encodings.cpu().numpy().astype(np.uint16))

# 4. Concatenate all batches into one large array
latent_dataset = np.concatenate(all_latent_codes, axis=0)
print(f"\n✅ Extraction complete! New dataset shape: {latent_dataset.shape}")

# 5. Save directly to Kaggle's working directory
np.save('/kaggle/working/celeba_8x8_latents.npy', latent_dataset)
print("Saved to /kaggle/working/celeba_8x8_latents.npy")

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import numpy as np

# ==========================================
# 1. The Sequence Dataset
# ==========================================
class LatentSequenceDataset(Dataset):
    def __init__(self, npy_path, codebook_size=512):
        print(f"Loading data from {npy_path}...")
        # Load the [202599, 8, 8] array
        self.data = np.load(npy_path).astype(np.int64)

        # Flatten the 8x8 grids into 1D sequences of length 64
        self.data = self.data.reshape(self.data.shape[0], 64)

        self.sos_token = codebook_size # Token 512

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sequence = self.data[idx]

        # Input: [SOS, t1, t2, ... t63]
        x = np.concatenate(([self.sos_token], sequence[:-1]))

        # Target: [t1, t2, t3, ... t64]
        y = sequence

        return torch.tensor(x, dtype=torch.long), torch.tensor(y, dtype=torch.long)

# ==========================================
# 2. The Mini-GPT Architecture
# ==========================================
class MiniGPT(nn.Module):
    def __init__(self, vocab_size=513, seq_len=64, embed_dim=256, num_heads=8, num_layers=6):
        super().__init__()

        # Token Embeddings (Vocab 0-511 + SOS token 512)
        self.token_emb = nn.Embedding(vocab_size, embed_dim)

        # Positional Embeddings (Tells the model WHERE the token is in the 8x8 grid)
        self.pos_emb = nn.Embedding(seq_len, embed_dim)

        # The Transformer Blocks
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=num_heads,
            dim_feedforward=embed_dim * 4,
            dropout=0.1,
            batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # Final output layer to predict the next token probability
        self.to_logits = nn.Linear(embed_dim, vocab_size)

    def forward(self, x):
        batch_size, seq_length = x.shape
        device = x.device

        # 1. Create position indices [0, 1, 2... 63]
        positions = torch.arange(0, seq_length, dtype=torch.long, device=device).unsqueeze(0).expand(batch_size, seq_length)

        # 2. Add Token + Positional embeddings
        embeddings = self.token_emb(x) + self.pos_emb(positions)

        # 3. Create a Causal Mask (Ensures token N cannot look ahead at token N+1)
        causal_mask = nn.Transformer.generate_square_subsequent_mask(seq_length, device=device)

        # 4. Pass through Transformer
        hidden_states = self.transformer(embeddings, mask=causal_mask, is_causal=True)

        # 5. Predict the next tokens
        logits = self.to_logits(hidden_states)
        return logits

# Initialize Data and Model
dataset = LatentSequenceDataset('/kaggle/input/datasets/vishal2028/checkpoints/celeba_8x8_latents (1).npy', codebook_size=512)
dataloader = DataLoader(dataset, batch_size=256, shuffle=True, num_workers=4, pin_memory=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
gpt_model = MiniGPT(vocab_size=513, seq_len=64).to(device)

print(f"Dataset Size: {len(dataset)} sequences")
print(f"MiniGPT Parameters: {sum(p.numel() for p in gpt_model.parameters()) / 1e6:.2f} Million")

import torch.optim as optim
import torch.nn as nn
import torch

# Hyperparameters
gpt_epochs = 10
gpt_lr = 3e-4

optimizer = optim.Adam(gpt_model.parameters(), lr=gpt_lr)
criterion = nn.CrossEntropyLoss()

# 1. Bring back the GradScaler for memory efficiency!
scaler = torch.amp.GradScaler('cuda')

gpt_model.train()
print("🚀 Starting Mini-GPT Training...")

for epoch in range(gpt_epochs):
    total_loss = 0

    for batch_idx, (x, y) in enumerate(dataloader):
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad(set_to_none=True)

        # 2. Mixed Precision Context
        with torch.autocast(device_type='cuda', dtype=torch.float16):
            logits = gpt_model(x)

            # Your perfect reshaping logic:
            loss = criterion(logits.view(-1, 513), y.view(-1))

        # Backward pass
        scaler.scale(loss).backward()

        # 3. Transformer Safety Net: Unscale and Clip Gradients
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(gpt_model.parameters(), max_norm=1.0)

        # Optimizer step
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item()

    avg_loss = total_loss / len(dataloader)
    print(f"Epoch [{epoch+1}/{gpt_epochs}] | GPT Loss: {avg_loss:.4f}")

print("🎉 GPT Training Complete!")

print(device)

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import torchvision.utils as vutils
import numpy as np
import torch.nn as nn

# 1. Ensure models are in evaluation mode
gpt_model.eval()
model.eval()

# Extract base models in case they are wrapped in DataParallel
base_vq_model = model.module if isinstance(model, nn.DataParallel) else model

num_samples = 16
seq_len = 64
sos_token = 512

print("🧠 Imagining new faces token by token...")

# 2. Start with a batch of SOS tokens
generated_sequence = torch.full((num_samples, 1), sos_token, dtype=torch.long, device=device)

with torch.no_grad():
    # 3. Autoregressive Loop: Generate 64 tokens one by one
    for i in range(seq_len):
        logits = gpt_model(generated_sequence)

        # We only care about the prediction for the LAST token
        next_token_logits = logits[:, -1, :]

        # Temperature sampling
        probs = F.softmax(next_token_logits / 1.0, dim=-1)

        # Force the model to NEVER sample the SOS token again
        probs[:, sos_token] = 0.0
        probs = probs / probs.sum(dim=-1, keepdim=True)

        # Sample the next token
        next_token = torch.multinomial(probs, num_samples=1)
        generated_sequence = torch.cat((generated_sequence, next_token), dim=1)

# 4. Remove SOS token and reshape to 8x8 latent grid
latent_indices = generated_sequence[:, 1:].reshape(num_samples, 8, 8)

# 5. Map the integer indices back to continuous 256-D Codebook vectors (OPTIMIZED)
# Passing [16, 8, 8] directly into the embedding returns [16, 8, 8, 256] instantly
quantized = base_vq_model.vq_layer.embedding(latent_indices)

# Permute to [Batch, Channels, Height, Width] for the convolutional decoder
quantized = quantized.permute(0, 3, 1, 2).contiguous()

# 6. Final Render: Decode latents into RGB pixels
fake_faces = base_vq_model.decoder(quantized)

# 7. Display the result
fake_grid = vutils.make_grid(fake_faces.cpu(), nrow=4, normalize=True)
plt.figure(figsize=(10, 10))
plt.imshow(np.transpose(fake_grid, (1, 2, 0)))
plt.axis("off")
plt.title("AI-Imagined Celebrity Faces")

# --- THE FIX: Save the image BEFORE showing it ---
plt.savefig('/kaggle/working/ai_imagined_faces.png', dpi=300, bbox_inches='tight')
print("💾 Masterpiece safely saved to /kaggle/working/ai_imagined_faces.png!")
# ------------------------------------------------

plt.show()

print(latent_dataset.max(), latent_dataset.min())